### PR TITLE
Sync PRs in the merge queue and document new behavior in README

### LINKED ISSUE #6: Update merge queue
As we merge PRs, this code could also update 2-3 of the next-in-line PRs to be merged that have `reviewed/wait-merge`.

It may also be beneficial to do this per-branch, so we update things targeting `main` as well as `release/v1.19` etc.

/cc @delvh

### PR DESCRIPTION
**Pull request by yardenshoham**
Backports are so old-news... We do all kinds of cool stuff now

Closes #6

### CODE REVIEW

**Comment by yardenshoham** [comment]
Couldn't test without an admin token for `go-gitea/gitea`
image

**Comment by yardenshoham** [comment]
Not sure if it'll work, let's merge and test in production

**Comment by jolheiser** [comment]
Is there any way to have multiple "queues"? 
For example, we can merge something into `main` and another thing into `1.19.x` without interfering with each other.

As well, I'm not sure if we need 3 anymore, the CI has been spruced up a bit and doesn't fail randomly as often. Maybe for the initial PR we just update 1, then we can increase it if needed?

**Comment by yardenshoham** [comment]
It'll always update the PR with the largest number in each milestone

**Comment by yardenshoham** [comment]
I will monitor this in the production logs

**Comment by yardenshoham** [comment]
It works!
image

**Pull request merged**
