### PR TITLE
Block pull requests as long as changes are requested

### PR DESCRIPTION
**Pull request by yardenshoham**
We add a new `lgtm/blocked` state that makes sure no pull request gets merged while it still has changes requested.
- #73

### CODE REVIEW

**Comment by yardenshoham** [comment]
I'm trying to think how to avoid what happened inhttps://github.com/go-gitea/gitea/pull/22664, it blocked the queue and was not ready for merge

**Comment by silverwind** [comment]
Don't think it can really be automated. We could block merge by regular mergers, and admins could merge even with the lgtm bot failing (because of the block).

**Comment by yardenshoham** [comment]
I understand, maybe we should sync a few PRs in the merge queue, not only the last one

**Comment by silverwind** [comment]
Wouldn't have closed this yet. If admins want the merge block reflected in LGTM bot and are willing to forcibly merge long-blocked PRs that are ready, we could do it.

Otherwise, I guess current situation is fine. A merger should just check the blocks, ask for unblock, and if there's no response within a few days, merge.

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
